version: '3.8'

services:
  webapp:
    build: .
    container_name: docker-workshop-demo
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=production
      - APP_VERSION=2.0.0
      - CUSTOM_MESSAGE=Welcome to Docker Workshop! 🚀
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

